version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: opendata
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7687:7687"
      - "7474:7474"  # Optional for accessing Neo4j browser
    volumes:
      - neo4j_data:/data

  postgres:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: opendata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres

volumes:
  mysql_data:
    driver: local
  neo4j_data:
    driver: local
  postgres_data:
    driver: local
